[project]
name = "gaussian-mae"
version = "0.0.1"

dependencies = [
    "einops",
    "numpy==1.26",
    "wandb",
    "tqdm",
    "python-dotenv",
    "omegaconf",
    "hydra-core",
    "pytorch_lightning"
]

[tool.setuptools.packages.find]
include = ["src/*"]